import { useMemo } from 'react';
import { AddToProject, type MaterialLine } from './ShelfAddToProject';
import { saveDrawerDesign } from '../services/api';
import {
  drawerProjectCutItems, drawerProjectTitle, toSavedDrawerDesign, type DrawerConfig, type DrawerHeightMode, type DrawerPlan,
} from '../lib/drawerUnit';
import type { LengthUnit } from '../lib/shelving';

interface Props {
  plan: DrawerPlan;
  config: DrawerConfig;
  units: LengthUnit;
  heightMode: DrawerHeightMode;
  initialProjectId?: number;
  costLines?: MaterialLine[];
  onClose: () => void;
}

export default function DrawerAddToProject({ plan, config, units, heightMode, initialProjectId, costLines, onClose }: Props) {
  const items = useMemo(() => drawerProjectCutItems(plan), [plan]);
  const title = drawerProjectTitle(plan, units);
  return (
    <AddToProject
      items={items}
      units={units}
      defaultTitle={title}
      newProjectDescription={`Generated by Drawer Builder: ${title.replace('Drawer unit ', '')}, on ${formatSlides(plan, units)}.`}
      noun="drawer unit"
      saveDesign={id => saveDrawerDesign(id, toSavedDrawerDesign(config, units, heightMode))}
      initialProjectId={initialProjectId}
      costLines={costLines}
      onClose={onClose}
    />
  );
}

function formatSlides(plan: DrawerPlan, units: LengthUnit): string {
  const inches = units === 'mm' ? `${Math.round(plan.slideLength * 25.4)} mm` : `${plan.slideLength}″`;
  return `${inches} LONTAN slides`;
}
