import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { AlertCircle, Check, FolderPlus, Loader2 } from 'lucide-react';
import { Button, SegmentedControl } from './ui';
import { addCutItem, createProject, deleteCutItem, getProject, listProjects, saveShelfDesign } from '../services/api';
import { isDemoMode } from '../demo/demoMode';
import {
  projectCutItems, shelfProjectTitle, toSavedShelfDesign, type LengthUnit, type ShelfConfig, type ShelfPlan,
} from '../lib/shelving';
import { describeSave, saveCutListToProject, type SaveMode } from '../lib/projectCutList';
import type { CutListItem, ProjectListItem } from '../types/project';

type Target = 'existing' | 'new';

const TARGET_OPTIONS = [
  { value: 'existing', label: 'Existing project' },
  { value: 'new', label: 'New project' },
] as const;

interface Props {
  plan: ShelfPlan;
  config: ShelfConfig;
  units: LengthUnit;
  onClose: () => void;
}

type Load<T> = { state: 'loading' } | { state: 'error'; message: string } | { state: 'ready'; value: T };

const errorText = (err: unknown) => (err instanceof Error && err.message ? err.message : 'Something went wrong.');

export default function ShelfAddToProject({ plan, config, units, onClose }: Props) {
  const demo = isDemoMode();
  const items = useMemo(() => projectCutItems(plan), [plan]);
  const pieceCount = items.reduce((sum, i) => sum + i.qty, 0);

  const [target, setTarget] = useState<Target>('existing');
  const [projects, setProjects] = useState<Load<ProjectListItem[]>>({ state: 'loading' });
  const [projectId, setProjectId] = useState<number | null>(null);
  const [existing, setExisting] = useState<Load<CutListItem[]> | null>(null);
  const [mode, setMode] = useState<SaveMode>('append');
  const [title, setTitle] = useState(() => shelfProjectTitle(plan, units));
  const [saving, setSaving] = useState(false);
  const [outcome, setOutcome] = useState<{ ok: boolean; text: string; projectId: number | null } | null>(null);
  const [reloadKey, setReloadKey] = useState(0);

  useEffect(() => {
    let cancelled = false;
    setProjects({ state: 'loading' });
    listProjects()
      .then(list => {
        if (cancelled) return;
        setProjects({ state: 'ready', value: list });
        if (list.length === 0) setTarget('new');
      })
      .catch(err => !cancelled && setProjects({ state: 'error', message: errorText(err) }));
    return () => { cancelled = true; };
  }, [reloadKey]);

  // The chosen project's current parts decide whether "replace" is offered.
  useEffect(() => {
    if (projectId == null) { setExisting(null); return; }
    let cancelled = false;
    setExisting({ state: 'loading' });
    getProject(projectId)
      .then(p => !cancelled && setExisting({ state: 'ready', value: p.cut_list ?? [] }))
      .catch(err => !cancelled && setExisting({ state: 'error', message: errorText(err) }));
    return () => { cancelled = true; };
  }, [projectId]);

  const existingParts = existing?.state === 'ready' ? existing.value : [];
  const selected = projects.state === 'ready' ? projects.value.find(p => p.id === projectId) : undefined;

  const blocker =
    demo ? 'Demo mode is read-only — sign in with Microsoft to save to a project.'
    : target === 'existing' && projectId == null ? 'Choose a project.'
    : target === 'existing' && existing?.state === 'loading' ? 'Checking that project’s cut list…'
    : target === 'existing' && existing?.state === 'error' ? `That project couldn’t be opened: ${existing.message}`
    : target === 'new' && title.trim() === '' ? 'Give the new project a title.'
    : null;

  const submit = async () => {
    if (blocker || saving) return;
    setSaving(true);
    setOutcome(null);
    let id = projectId;
    let name = selected?.title ?? '';
    try {
      if (target === 'new') {
        const created = await createProject({
          title: title.trim(),
          description: `Generated by Shelf Builder: ${plan.bays.length} bays, ${shelfProjectTitle(plan, units).replace('Shelving unit ', '')}.`,
          source_url: '',
          cut_plan_url: '',
          status: 'planning',
          difficulty: 'Intermediate',
          estimated_hours: 0,
          wood_types: ['Plywood'],
          tools_needed: [],
        });
        id = created.id;
        name = created.title;
      }
    } catch (err) {
      setOutcome({ ok: false, text: `The project couldn’t be created: ${errorText(err)}`, projectId: null });
      setSaving(false);
      return;
    }

    const saveMode: SaveMode = target === 'new' ? 'append' : mode;
    const result = await saveCutListToProject(
      { add: addCutItem, remove: deleteCutItem },
      id!,
      items,
      target === 'new' ? [] : existingParts,
      saveMode,
    );
    let text = describeSave(result, name, saveMode);
    let ok = !result.error && result.removeFailed === 0;
    if (!result.error) {
      // The design itself powers the project page's 3D preview.
      try {
        await saveShelfDesign(id!, toSavedShelfDesign(config, units));
        text += ' The 3D preview is on the project page.';
      } catch (err) {
        ok = false;
        text += ` The parts are saved, but the 3D design couldn’t be: ${errorText(err)} Add it again with “Replace them” to retry.`;
      }
    }
    setOutcome({ ok, text, projectId: id });
    setSaving(false);
    if (target === 'new' && id != null) {
      // The project now exists: switch to it so another click adds to it instead of creating a second one.
      setReloadKey(k => k + 1);
      setTarget('existing');
      setProjectId(id);
    } else if (id != null) {
      // Refresh the count so a second click shows the new state.
      getProject(id).then(p => setExisting({ state: 'ready', value: p.cut_list ?? [] })).catch(() => undefined);
    }
  };

  const partsLabel = `${items.length} part${items.length === 1 ? '' : 's'}`;

  return (
    <section className="shelf-add-project" aria-labelledby="shelf-add-project-title">
      <header>
        <h3 id="shelf-add-project-title">Add cut list to a project</h3>
        <p>
          Saves {partsLabel} ({pieceCount} pieces) as plywood, in inches
          {units === 'mm' ? ' — project pages and their sheet layout work in inches' : ''}.
          The design is saved too, for a 3D preview on the project page. Part notes such as dado reminders
          aren’t saved; project parts have no notes field.
        </p>
      </header>

      <SegmentedControl label="Save to" value={target} options={TARGET_OPTIONS} onChange={setTarget} />

      {target === 'existing' ? (
        <div className="shelf-add-project-fields">
          {projects.state === 'loading' && <p className="is-muted" role="status">Loading your projects…</p>}
          {projects.state === 'error' && (
            <p className="shelf-add-project-error" role="alert">
              <AlertCircle size={16} aria-hidden="true" /> Your projects couldn’t be loaded: {projects.message}{' '}
              <button type="button" className="shelf-link-button" onClick={() => setReloadKey(k => k + 1)}>Try again</button>
            </p>
          )}
          {projects.state === 'ready' && projects.value.length === 0 && (
            <p className="is-muted">You don’t have any projects yet — choose New project.</p>
          )}
          {projects.state === 'ready' && projects.value.length > 0 && (
            <label className="form-field">
              <span className="form-field-label">Project</span>
              <select
                value={projectId ?? ''}
                onChange={e => {
                  setProjectId(e.target.value ? Number(e.target.value) : null);
                  setMode('append');
                  setOutcome(null);
                }}
              >
                <option value="">Choose a project…</option>
                {projects.value.map(p => (
                  <option key={p.id} value={p.id}>
                    {p.title}{p.parts_count > 0 ? ` — ${p.parts_count} part${p.parts_count === 1 ? '' : 's'}` : ''}
                  </option>
                ))}
              </select>
            </label>
          )}
          {existing?.state === 'ready' && existingParts.length > 0 && (
            <fieldset className="shelf-add-project-mode">
              <legend className="form-field-label">“{selected?.title}” already has {existingParts.length} part{existingParts.length === 1 ? '' : 's'}</legend>
              <label className="shelf-toggle">
                <input type="radio" name="shelf-save-mode" checked={mode === 'append'} onChange={() => setMode('append')} />
                <span><span className="shelf-toggle-label">Add after them</span><small>Keeps the existing parts; the shelf parts go at the end.</small></span>
              </label>
              <label className="shelf-toggle">
                <input type="radio" name="shelf-save-mode" checked={mode === 'replace'} onChange={() => setMode('replace')} />
                <span>
                  <span className="shelf-toggle-label">Replace them</span>
                  <small>Deletes those {existingParts.length} parts, but only after every new part has saved.</small>
                </span>
              </label>
            </fieldset>
          )}
        </div>
      ) : (
        <label className="form-field shelf-add-project-fields">
          <span className="form-field-label">New project title</span>
          <input value={title} onChange={e => { setTitle(e.target.value); setOutcome(null); }} />
          <small>Created as a Planning project with this cut list.</small>
        </label>
      )}

      <div className="shelf-add-project-actions">
        <Button variant="primary" onClick={() => void submit()} disabled={blocker !== null || saving}>
          {saving ? <Loader2 size={16} className="spin" aria-hidden="true" /> : <FolderPlus size={16} aria-hidden="true" />}
          {saving ? 'Saving…'
            : target === 'new' ? `Create project with ${partsLabel}`
            : mode === 'replace' && existingParts.length > 0 ? `Replace with ${partsLabel}`
            : `Add ${partsLabel}`}
        </Button>
        <Button variant="ghost" onClick={onClose} disabled={saving}>Close</Button>
        {blocker && !saving && <span className="is-muted shelf-add-project-hint">{blocker}</span>}
      </div>

      <div role="status" aria-live="polite">
        {outcome && (
          <p className={outcome.ok ? 'shelf-add-project-ok' : 'shelf-add-project-error'}>
            {outcome.ok ? <Check size={16} aria-hidden="true" /> : <AlertCircle size={16} aria-hidden="true" />}
            <span>
              {outcome.text}{' '}
              {outcome.projectId != null && <Link to={`/projects/${outcome.projectId}`}>Open project</Link>}
            </span>
          </p>
        )}
      </div>
    </section>
  );
}
